language: node_js

script:
  - cd dummy
  - bash <(curl -s https://blackbaud-bobbyearl.github.io/testing-travis/test.sh)
  - node test.js

branches:
  only:
    - master
    - /^v[0-9]+\.[0-9]+\.[0-9]+.*/
